### ISSUE TITLE
训练自己的数据出错

### ISSUE THREAD

**Issue by RobinHan24** [BBuf/Keras-Semantic-Segmentation#1]
您好，感谢您的开源。使用您自带的数据集训练，没有错误。使用我自己的数据训练，出现以下错误，ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (2, 1)，我的样本数据height  width是不固定的，这个有影响吗，谢谢。两类，一类是物体，另一类是背景。

**Comment by BBuf** [comment]
你好，训练数据集的长宽需要固定，且长宽必须为32的倍数。

**Comment by BBuf** [comment]
你也可以选择修改LoadBatches.py 增加对输入数据的resize操作。
