### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by kkyiss** [BBuf/Keras-Semantic-Segmentation#2]
Hi @BBuf ,
According to the paper said, it ran 14.6 fps on 640 x 360
but as for your dataset which is 3 fps(0.55) on 512 x 512

The fps seems a bit slowly compare to the paper,
how do you think about that?

Again, thanks for your sharing and appreciate for any replies!

**Comment by BBuf** [comment]
the paper has used gpu, but I test the enet running speed in core-i7(cpu)。

**Comment by kkyiss** [comment]
gotcha!
