### ISSUE TITLE
PSPnet和FCN32运行出现问题

### ISSUE THREAD

**Issue by AHNUXFF** [BBuf/Keras-Semantic-Segmentation#4]
你好，
PSPnet运行错误提示：
def PSPNet(nClasses, optimizer=None, input_width=384, input_height=384):
    assert input_height%192 == 0
    assert input_width%192 == 0
AssertionError: 
我的input_width=256
FCN32运行错误提示：
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'block2_pool_6/MaxPool' (op: 'MaxPool') with input shapes: [?,1,128,128].
我的是tensorflow-gpu(1.4)+keras(2.3) 
请问大神怎么调试，期望您的回复。

**Comment by BBuf** [comment]
你要用这个网络的话，长宽必须是192的倍数，不难会出现维度不匹配的问题，要么你把你的图片resize到192，要么你修改一下Pool尺寸什么的，但是我不保证修改之后效果不会变差。
