### ISSUE TITLE
issue in segnet

### ISSUE THREAD

**Issue by cgcodeboy** [BBuf/Keras-Semantic-Segmentation#7]
The ''upsamping'' scheme adopted in segnet is UnPooling but not just UpSampling. You can see the different between them. 
![image](https://user-images.githubusercontent.com/23149398/70371199-415a6800-190b-11ea-9cdb-5de19164c130.png)

**Comment by BBuf** [comment]
Thanks，I will try to add it。

**Comment by BBuf** [comment]
I fixed the bug。
